export { getSurreal, closeSurreal } from './client.js'
export * from './tenant.js'
export * from './schema-registry.js'
export * from './platform-status.js'
export * from './resource-types.js'
export * from './permission-resolver.js'
export * from './permissions.js'
export * from './user-groups.js'
