// packages/db/src/schema-definitions.ts
import type {
  ColumnDefinition,
  RelationDefinition,
  SortSetting,
  TableColumnConfig,
  TableSchemaDefinition,
  TableViewConfig,
  ViewConfig,
  ViewDefinition,
} from 'shared'

export type {
  ColumnDefinition,
  RelationDefinition,
  SortSetting,
  TableColumnConfig,
  TableSchemaDefinition,
  TableViewConfig,
  ViewConfig,
  ViewDefinition,
}

/** System columns added automatically to every table. */
export const SYSTEM_COLUMNS: ColumnDefinition[] = [
  { name: 'id', dbType: 'record', displayType: 'text', system: true, optional: false, hidden: false },
  { name: 'createdAt', dbType: 'datetime', displayType: 'date', system: true, optional: true, hidden: true },
  { name: 'createdBy', dbType: 'record', displayType: 'relation', system: true, optional: true, hidden: true },
  { name: 'updatedAt', dbType: 'datetime', displayType: 'date', system: true, optional: true, hidden: true },
  { name: 'updatedBy', dbType: 'record', displayType: 'relation', system: true, optional: true, hidden: true },
  { name: 'deletedAt', dbType: 'datetime', displayType: 'date', system: true, optional: true, hidden: true },
  { name: 'deletedBy', dbType: 'record', displayType: 'relation', system: true, optional: true, hidden: true },
]

/** Platform-level table schemas, available across all tenants. */
export const PLATFORM_TABLE_SCHEMAS: TableSchemaDefinition[] = [
  {
    name: 'companies',
    label: 'Companies',
    columns: [
      { name: 'name', dbType: 'string', displayType: 'text', optional: true },
      { name: 'slug', dbType: 'string', displayType: 'tag', optional: true, unique: true, config: { displayType: 'tag', defaultColor: 'gray' } },
      { name: 'namespace', dbType: 'string', displayType: 'text', optional: true },
      { name: 'status', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'Active', value: 'active' }, { label: 'Inactive', value: 'inactive' }] } },
    ],
    relations: undefined,
  },
  {
    name: 'sessions',
    label: 'Sessions',
    columns: [
      { name: 'refreshTokenHash', dbType: 'string', displayType: 'text', optional: true, unique: true },
      { name: 'accessTokenJti', dbType: 'string', displayType: 'text', optional: true },
      { name: 'accountId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨sessions:accountId:accounts:id⟩' } },
      { name: 'profileId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨sessions:profileId:user_profiles:id⟩' } },
      { name: 'platformUserId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨sessions:platformUserId:platform_users:id⟩' } },
      { name: 'email', dbType: 'string', displayType: 'text', optional: true },
      { name: 'type', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'user', value: 'user' }, { label: 'impersonation', value: 'impersonation' }] } },
      { name: 'impersonatorId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨sessions:impersonatorId:user_profiles:id⟩' } },
      { name: 'companyId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨sessions:companyId:companies:id⟩' } },
      { name: 'deviceFingerprint', dbType: 'string', displayType: 'text', optional: true },
      { name: 'deviceName', dbType: 'string', displayType: 'text', optional: true },
      { name: 'ip', dbType: 'string', displayType: 'text', optional: true },
      { name: 'userAgent', dbType: 'string', displayType: 'text', optional: true },
      { name: 'refreshExpiresAt', dbType: 'datetime', displayType: 'date', optional: true },
      { name: 'accessExpiresAt', dbType: 'datetime', displayType: 'date', optional: true },
      { name: 'lastUsedAt', dbType: 'datetime', displayType: 'date', optional: true },
      { name: 'revokedAt', dbType: 'datetime', displayType: 'date', optional: true },
      { name: 'revokeReason', dbType: 'string', displayType: 'text', optional: true },
    ],
    relations: [
      { kind: 'reference', fromColumn: 'accountId', toTable: 'accounts', toColumn: 'id', type: 'many-to-many', fromTable: 'sessions' },
      { kind: 'reference', fromColumn: 'profileId', toTable: 'user_profiles', toColumn: 'id', type: 'many-to-many', fromTable: 'sessions' },
      { kind: 'reference', fromColumn: 'platformUserId', toTable: 'platform_users', toColumn: 'id', type: 'many-to-many', fromTable: 'sessions' },
      { kind: 'reference', fromColumn: 'impersonatorId', toTable: 'user_profiles', toColumn: 'id', type: 'many-to-many', fromTable: 'sessions' },
      { kind: 'reference', fromColumn: 'companyId', toTable: 'companies', toColumn: 'id', type: 'many-to-many', fromTable: 'sessions' },
    ],
  },
  {
    name: 'platform_users',
    label: 'Platform Users',
    columns: [
      { name: 'email', dbType: 'string', displayType: 'email', optional: true, unique: true },
      { name: 'password', dbType: 'string', displayType: 'text', optional: true, hidden: true },
    ],
    relations: undefined,
  },
  {
    name: 'admin_user_groups',
    label: 'Admin User Groups',
    columns: [
      { name: 'name', dbType: 'string', displayType: 'text', optional: true },
      { name: 'description', dbType: 'string', displayType: 'text', optional: true },
    ],
    relations: undefined,
  },
  {
    name: 'resource_types',
    label: 'Resource Types',
    columns: [
      { name: 'name', dbType: 'string', displayType: 'text', optional: true },
      { name: 'table', dbType: 'string', displayType: 'text', optional: true },
      { name: 'hasRecordId', dbType: 'boolean', displayType: 'checkbox', optional: true },
      { name: 'bitMapping', dbType: 'array', displayType: 'json', optional: true },
      { name: 'defaultGroups', dbType: 'array', displayType: 'json', optional: true },
      { name: 'parentResourceType', dbType: 'string', displayType: 'text', optional: true },
      { name: 'isSystem', dbType: 'boolean', displayType: 'checkbox', optional: true },
      { name: 'scope', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'Platform', value: 'platform' }, { label: 'Tenant', value: 'tenant' }] } },
    ],
    relations: undefined,
  },
  {
    name: 'accounts',
    label: 'Accounts',
    columns: [
      { name: 'provider', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'email', value: 'email' }, { label: 'oauth_google', value: 'oauth_google' }, { label: 'oauth_github', value: 'oauth_github' }, { label: 'phone', value: 'phone' }] } },
      { name: 'providerKey', dbType: 'string', displayType: 'text', optional: true },
      { name: 'credential', dbType: 'string', displayType: 'text', optional: true, hidden: true },
      { name: 'profileId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨accounts:profileId:user_profiles:id⟩' } },
    ],
    relations: [
      { kind: 'reference', fromColumn: 'profileId', toTable: 'user_profiles', toColumn: 'id', type: 'many-to-many', fromTable: 'accounts' },
    ],
  },
  {
    name: 'user_profiles',
    label: 'User Profiles',
    columns: [
      { name: 'name', dbType: 'string', displayType: 'text', optional: true },
      { name: 'gender', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'male', value: 'male' }, { label: 'female', value: 'female' }, { label: 'other', value: 'other' }, { label: 'prefer_not_to_say', value: 'prefer_not_to_say' }] } },
      { name: 'birthday', dbType: 'datetime', displayType: 'date', optional: true },
      { name: 'preferences', dbType: 'object', displayType: 'text', optional: true },
    ],
    relations: undefined,
  },
  {
    name: 'workflow_designs',
    label: 'Workflow Designs',
    columns: [
      { name: 'name', dbType: 'string', displayType: 'text', optional: true },
      { name: 'xstateConfig', dbType: 'object', displayType: 'json', optional: true },
      { name: 'starts', dbType: 'array', displayType: 'json', optional: true, fields: [
        { name: 'type', dbType: 'string', displayType: 'select', optional: true, config: { options: [{ label: 'db_trigger', value: 'db_trigger' }, { label: 'user_trigger', value: 'user_trigger' }, { label: 'cron', value: 'cron' }, { label: 'webhook', value: 'webhook' }] } },
        { name: 'startState', dbType: 'string', displayType: 'text', optional: true },
        { name: 'options', dbType: 'object', displayType: 'json', optional: true },
      ] },
    ],
    relations: undefined,
  },
  {
    name: 'workflow_instances',
    label: 'Workflow Instances',
    columns: [
      { name: 'designId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨workflow_instances:designId:workflow_designs:id⟩' } },
      { name: 'status', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'pending', value: 'pending' }, { label: 'running', value: 'running' }, { label: 'waiting', value: 'waiting' }, { label: 'done', value: 'done' }, { label: 'error', value: 'error' }] } },
      { name: 'currentState', dbType: 'string', displayType: 'text', optional: true },
      { name: 'context', dbType: 'object', displayType: 'json', optional: true },
      { name: 'triggerBy', dbType: 'object', displayType: 'json', optional: true, fields: [
        { name: 'type', dbType: 'string', displayType: 'select', optional: true, config: { options: [{ label: 'db_trigger', value: 'db_trigger' }, { label: 'user_trigger', value: 'user_trigger' }, { label: 'cron', value: 'cron' }, { label: 'webhook', value: 'webhook' }] } },
        { name: 'startState', dbType: 'string', displayType: 'text', optional: true },
      ] },
      { name: 'namespace', dbType: 'string', displayType: 'text', optional: true },
      { name: 'companyId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨workflow_instances:companyId:companies:id⟩' } },
    ],
    relations: [
      { kind: 'reference', fromColumn: 'designId', toTable: 'workflow_designs', toColumn: 'id', type: 'many-to-many', fromTable: 'workflow_instances' },
      { kind: 'reference', fromColumn: 'companyId', toTable: 'companies', toColumn: 'id', type: 'many-to-many', fromTable: 'workflow_instances' },
    ],
  },
  {
    name: 'user_tasks',
    label: 'User Tasks',
    columns: [
      { name: 'instanceId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨user_tasks:instanceId:workflow_instances:id⟩' } },
      { name: 'type', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'approval', value: 'approval' }, { label: 'review', value: 'review' }, { label: 'manual', value: 'manual' }] } },
      { name: 'status', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'pending', value: 'pending' }, { label: 'completed', value: 'completed' }, { label: 'cancelled', value: 'cancelled' }, { label: 'rejected', value: 'rejected' }] } },
      { name: 'tableName', dbType: 'string', displayType: 'text', optional: true },
      { name: 'recordId', dbType: 'record', displayType: 'text', optional: true },
      { name: 'designId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨user_tasks:designId:workflow_designs:id⟩' } },
      { name: 'resolvedAt', dbType: 'datetime', displayType: 'date', optional: true },
    ],
    relations: [
      { kind: 'reference', fromColumn: 'instanceId', toTable: 'workflow_instances', toColumn: 'id', type: 'many-to-many', fromTable: 'user_tasks' },
      { kind: 'reference', fromColumn: 'designId', toTable: 'workflow_designs', toColumn: 'id', type: 'many-to-many', fromTable: 'user_tasks' },
    ],
  },
  {
    name: 'workflow_actions',
    label: 'Workflow Actions',
    columns: [
      { name: 'instanceId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨workflow_actions:instanceId:workflow_instances:id⟩' } },
      { name: 'designId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨workflow_actions:designId:workflow_designs:id⟩' } },
      { name: 'stateId', dbType: 'string', displayType: 'text', optional: true },
      { name: 'action', dbType: 'string', displayType: 'text', optional: true },
      { name: 'params', dbType: 'object', displayType: 'text', optional: true },
      { name: 'status', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'started', value: 'started' }, { label: 'completed', value: 'completed' }, { label: 'failed', value: 'failed' }] } },
      { name: 'inputContext', dbType: 'object', displayType: 'text', optional: true },
      { name: 'outputContext', dbType: 'object', displayType: 'text', optional: true },
      { name: 'outputData', dbType: 'object', displayType: 'text', optional: true },
      { name: 'resultEvent', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'ok', value: 'ok' }, { label: 'error', value: 'error' }, { label: 'true', value: 'true' }, { label: 'false', value: 'false' }] } },
      { name: 'errorMessage', dbType: 'string', displayType: 'text', optional: true },
      { name: 'startedAt', dbType: 'datetime', displayType: 'date', optional: true },
      { name: 'completedAt', dbType: 'datetime', displayType: 'date', optional: true },
    ],
    relations: [
      { kind: 'reference', fromColumn: 'instanceId', toTable: 'workflow_instances', toColumn: 'id', type: 'many-to-many', fromTable: 'workflow_actions' },
      { kind: 'reference', fromColumn: 'designId', toTable: 'workflow_designs', toColumn: 'id', type: 'many-to-many', fromTable: 'workflow_actions' },
    ],
  },
  {
    name: 'health_checks',
    label: 'Health Checks',
    columns: [
      { name: 'service', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'surrealdb', value: 'surrealdb' }, { label: 'restate', value: 'restate' }, { label: 'workflow-runtime', value: 'workflow-runtime' }, { label: 'api', value: 'api' }] } },
      { name: 'status', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'healthy', value: 'healthy' }, { label: 'unhealthy', value: 'unhealthy' }] } },
      { name: 'checkedAt', dbType: 'datetime', displayType: 'date', optional: true },
      { name: 'responseTimeMs', dbType: 'number', displayType: 'number', optional: true },
      { name: 'message', dbType: 'string', displayType: 'text', optional: true },
      { name: 'details', dbType: 'object', displayType: 'text', optional: true },
    ],
    relations: undefined,
  },
]

/** Tenant-level table schemas, provisioned inside each company namespace. */
export const TENANT_TABLE_SCHEMAS: TableSchemaDefinition[] = [
  {
    name: 'members',
    label: 'Members',
    columns: [
      { name: 'profileId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨members:profileId:user_profiles:id⟩' } },
      { name: 'email', dbType: 'string', displayType: 'email', optional: true },
      { name: 'role', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'owner', value: 'owner' }, { label: 'admin', value: 'admin' }, { label: 'member', value: 'member' }] } },
      { name: 'status', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'pending', value: 'pending' }, { label: 'active', value: 'active' }, { label: 'inactive', value: 'inactive' }] } },
      { name: 'inviteCode', dbType: 'string', displayType: 'text', optional: true, unique: true },
      { name: 'joinedAt', dbType: 'datetime', displayType: 'date', optional: true },
      { name: 'invitedBy', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨members:invitedBy:members:id⟩' } },
    ],
    relations: [
      { kind: 'reference', fromColumn: 'profileId', toTable: 'user_profiles', toColumn: 'id', type: 'many-to-many', fromTable: 'members' },
      { kind: 'reference', fromColumn: 'invitedBy', toTable: 'members', toColumn: 'id', type: 'one-to-many', fromTable: 'members' },
    ],
  },
  {
    name: 'sessions',
    label: 'Sessions',
    columns: [
      { name: 'platformSessionId', dbType: 'string', displayType: 'text', optional: true },
      { name: 'memberId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨sessions:memberId:members:id⟩' } },
      { name: 'profileId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨sessions:profileId:user_profiles:id⟩' } },
      { name: 'email', dbType: 'string', displayType: 'text', optional: true },
      { name: 'companyId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨sessions:companyId:companies:id⟩' } },
      { name: 'type', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'user', value: 'user' }, { label: 'impersonation', value: 'impersonation' }] } },
      { name: 'impersonatorId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨sessions:impersonatorId:members:id⟩' } },
      { name: 'deviceFingerprint', dbType: 'string', displayType: 'text', optional: true },
      { name: 'deviceName', dbType: 'string', displayType: 'text', optional: true },
      { name: 'ip', dbType: 'string', displayType: 'text', optional: true },
      { name: 'userAgent', dbType: 'string', displayType: 'text', optional: true },
      { name: 'lastUsedAt', dbType: 'datetime', displayType: 'date', optional: true },
      { name: 'revokedAt', dbType: 'datetime', displayType: 'date', optional: true },
      { name: 'revokeReason', dbType: 'string', displayType: 'text', optional: true },
    ],
    relations: [
      { kind: 'reference', fromColumn: 'memberId', toTable: 'members', toColumn: 'id', type: 'many-to-many', fromTable: 'sessions' },
      { kind: 'reference', fromColumn: 'profileId', toTable: 'user_profiles', toColumn: 'id', type: 'many-to-many', fromTable: 'sessions' },
      { kind: 'reference', fromColumn: 'companyId', toTable: 'companies', toColumn: 'id', type: 'many-to-many', fromTable: 'sessions' },
      { kind: 'reference', fromColumn: 'impersonatorId', toTable: 'members', toColumn: 'id', type: 'many-to-many', fromTable: 'sessions' },
    ],
  },
  {
    name: 'workflow_designs',
    label: 'Workflow Designs',
    columns: [
      { name: 'name', dbType: 'string', displayType: 'text', optional: true },
      { name: 'xstateConfig', dbType: 'object', displayType: 'json', optional: true },
      { name: 'starts', dbType: 'array', displayType: 'json', optional: true, fields: [
        { name: 'type', dbType: 'string', displayType: 'select', optional: true, config: { options: [{ label: 'db_trigger', value: 'db_trigger' }, { label: 'user_trigger', value: 'user_trigger' }, { label: 'cron', value: 'cron' }, { label: 'webhook', value: 'webhook' }] } },
        { name: 'startState', dbType: 'string', displayType: 'text', optional: true },
        { name: 'options', dbType: 'object', displayType: 'json', optional: true },
      ] },
    ],
    relations: undefined,
  },
  {
    name: 'workflow_instances',
    label: 'Workflow Instances',
    columns: [
      { name: 'designId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨workflow_instances:designId:workflow_designs:id⟩' } },
      { name: 'status', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'pending', value: 'pending' }, { label: 'running', value: 'running' }, { label: 'waiting', value: 'waiting' }, { label: 'done', value: 'done' }, { label: 'error', value: 'error' }] } },
      { name: 'currentState', dbType: 'string', displayType: 'text', optional: true },
      { name: 'context', dbType: 'object', displayType: 'json', optional: true },
      { name: 'triggerBy', dbType: 'object', displayType: 'json', optional: true, fields: [
        { name: 'type', dbType: 'string', displayType: 'select', optional: true, config: { options: [{ label: 'db_trigger', value: 'db_trigger' }, { label: 'user_trigger', value: 'user_trigger' }, { label: 'cron', value: 'cron' }, { label: 'webhook', value: 'webhook' }] } },
        { name: 'startState', dbType: 'string', displayType: 'text', optional: true },
      ] },
      { name: 'namespace', dbType: 'string', displayType: 'text', optional: true },
      { name: 'companyId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨workflow_instances:companyId:companies:id⟩' } },
    ],
    relations: [
      { kind: 'reference', fromColumn: 'designId', toTable: 'workflow_designs', toColumn: 'id', type: 'many-to-many', fromTable: 'workflow_instances' },
      { kind: 'reference', fromColumn: 'companyId', toTable: 'companies', toColumn: 'id', type: 'many-to-many', fromTable: 'workflow_instances' },
    ],
  },
  {
    name: 'user_tasks',
    label: 'User Tasks',
    columns: [
      { name: 'instanceId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨user_tasks:instanceId:workflow_instances:id⟩' } },
      { name: 'type', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'approval', value: 'approval' }, { label: 'review', value: 'review' }, { label: 'manual', value: 'manual' }] } },
      { name: 'status', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'pending', value: 'pending' }, { label: 'completed', value: 'completed' }, { label: 'cancelled', value: 'cancelled' }, { label: 'rejected', value: 'rejected' }] } },
      { name: 'tableName', dbType: 'string', displayType: 'text', optional: true },
      { name: 'recordId', dbType: 'record', displayType: 'text', optional: true },
      { name: 'designId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨user_tasks:designId:workflow_designs:id⟩' } },
      { name: 'resolvedAt', dbType: 'datetime', displayType: 'date', optional: true },
    ],
    relations: [
      { kind: 'reference', fromColumn: 'instanceId', toTable: 'workflow_instances', toColumn: 'id', type: 'many-to-many', fromTable: 'user_tasks' },
      { kind: 'reference', fromColumn: 'designId', toTable: 'workflow_designs', toColumn: 'id', type: 'many-to-many', fromTable: 'user_tasks' },
    ],
  },
  {
    name: 'workflow_actions',
    label: 'Workflow Actions',
    columns: [
      { name: 'instanceId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨workflow_actions:instanceId:workflow_instances:id⟩' } },
      { name: 'designId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨workflow_actions:designId:workflow_designs:id⟩' } },
      { name: 'stateId', dbType: 'string', displayType: 'text', optional: true },
      { name: 'action', dbType: 'string', displayType: 'text', optional: true },
      { name: 'params', dbType: 'object', displayType: 'text', optional: true },
      { name: 'status', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'started', value: 'started' }, { label: 'completed', value: 'completed' }, { label: 'failed', value: 'failed' }] } },
      { name: 'inputContext', dbType: 'object', displayType: 'text', optional: true },
      { name: 'outputContext', dbType: 'object', displayType: 'text', optional: true },
      { name: 'outputData', dbType: 'object', displayType: 'text', optional: true },
      { name: 'resultEvent', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'ok', value: 'ok' }, { label: 'error', value: 'error' }, { label: 'true', value: 'true' }, { label: 'false', value: 'false' }] } },
      { name: 'errorMessage', dbType: 'string', displayType: 'text', optional: true },
      { name: 'startedAt', dbType: 'datetime', displayType: 'date', optional: true },
      { name: 'completedAt', dbType: 'datetime', displayType: 'date', optional: true },
    ],
    relations: [
      { kind: 'reference', fromColumn: 'instanceId', toTable: 'workflow_instances', toColumn: 'id', type: 'many-to-many', fromTable: 'workflow_actions' },
      { kind: 'reference', fromColumn: 'designId', toTable: 'workflow_designs', toColumn: 'id', type: 'many-to-many', fromTable: 'workflow_actions' },
    ],
  },
  {
    name: 'permission_groups',
    label: 'Permission Groups',
    columns: [
      { name: 'resourceType', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: ['admin_user', 'admin_user_detail', 'admin_user_group', 'admin_user_group_detail', 'company', 'company_member', 'member', 'platform', 'tenant', 'user_group', 'user_group_detail', 'workflow_design', 'workflow_design_detail'].map((r) => ({ label: r, value: r })) } },
      { name: 'recordId', dbType: 'string', displayType: 'text', optional: true },
      { name: 'name', dbType: 'string', displayType: 'text', optional: true },
      { name: 'isSystem', dbType: 'boolean', displayType: 'checkbox', optional: true },
      { name: 'description', dbType: 'string', displayType: 'text', optional: true },
    ],
    relations: undefined,
  },
  {
    name: 'resource_types',
    label: 'Resource Types',
    columns: [
      { name: 'name', dbType: 'string', displayType: 'text', optional: true },
      { name: 'table', dbType: 'string', displayType: 'text', optional: true },
      { name: 'hasRecordId', dbType: 'boolean', displayType: 'checkbox', optional: true },
      { name: 'bitMapping', dbType: 'array', displayType: 'json', optional: true },
      { name: 'defaultGroups', dbType: 'array', displayType: 'json', optional: true },
      { name: 'parentResourceType', dbType: 'string', displayType: 'text', optional: true },
      { name: 'isSystem', dbType: 'boolean', displayType: 'checkbox', optional: true },
      { name: 'scope', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'Platform', value: 'platform' }, { label: 'Tenant', value: 'tenant' }] } },
    ],
    relations: undefined,
  },
  {
    name: 'user_groups',
    label: 'User Groups',
    columns: [
      { name: 'name', dbType: 'string', displayType: 'text', optional: true },
      { name: 'description', dbType: 'string', displayType: 'text', optional: true },
    ],
    relations: undefined,
  },
  {
    name: '_views',
    label: 'Views',
    columns: [
      { name: 'table', dbType: 'string', displayType: 'text', optional: true },
      { name: 'type', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'table', value: 'table' }] } },
      { name: 'name', dbType: 'string', displayType: 'text', optional: true },
      { name: 'description', dbType: 'string', displayType: 'text', optional: true },
      { name: 'isDefault', dbType: 'boolean', displayType: 'checkbox', optional: true, defaultValue: false },
      { name: 'config', dbType: 'object', displayType: 'json', optional: true },
      { name: 'group', dbType: 'object', displayType: 'json', optional: true },
      { name: 'filter', dbType: 'object', displayType: 'json', optional: true },
      { name: 'sort', dbType: 'array', displayType: 'json', optional: true },
    ],
    relations: undefined,
  },
  {
    name: 'company_policies',
    label: 'Company Policies',
    columns: [
      { name: 'companyId', dbType: 'record', displayType: 'relation', optional: true, config: { relationId: '_relations:⟨company_policies:companyId:companies:id⟩' } },
      { name: 'maxSessions', dbType: 'number', displayType: 'number', optional: true },
      { name: 'sessionOverflowAction', dbType: 'string', displayType: 'select', optional: true, config: { displayType: 'select', options: [{ label: 'revoke_oldest', value: 'revoke_oldest' }, { label: 'reject', value: 'reject' }] } },
      { name: 'allowImpersonation', dbType: 'boolean', displayType: 'checkbox', optional: true },
      { name: 'allowApiKeys', dbType: 'boolean', displayType: 'checkbox', optional: true },
    ],
    relations: [
      { kind: 'reference', fromColumn: 'companyId', toTable: 'companies', toColumn: 'id', type: 'many-to-many', fromTable: 'company_policies' },
    ],
  },
]

export const GRAPH_RELATIONS: RelationDefinition[] = [
  {
    kind: 'graph',
    name: 'groups',
    fromTable: 'platform_users',
    toTable: 'admin_user_groups',
    linkTable: 'admin_user_group_memberships',
    type: 'many-to-many',
  },
  {
    kind: 'graph',
    name: 'members',
    fromTable: 'user_groups',
    toTable: 'members',
    linkTable: 'user_group_memberships',
    type: 'many-to-many',
  },
  {
    kind: 'graph',
    name: 'permissions',
    fromTable: 'permission_groups',
    toTable: 'resources',
    linkTable: 'permission_apply_to',
    type: 'many-to-many',
  },
  {
    kind: 'graph',
    name: 'parents',
    fromTable: 'resources',
    toTable: 'resources',
    linkTable: 'resource_parent',
    type: 'many-to-many',
  },
  {
    kind: 'graph',
    name: 'assignments',
    fromTable: 'members',
    toTable: 'permission_groups',
    linkTable: 'permission_assignments',
    type: 'many-to-many',
  },
]
