export {
  RESOURCE_CATALOG,
  PLATFORM_CATALOG,
  TENANT_CATALOG,
  resourceType,
  actionValue,
  actionsToBitmask,
  bitmaskToActions,
  hasAction,
  allActionsBitmask,
  defaultGroups,
  type ResourceType,
  type PermissionAction,
  type ResourceTypeDefinition,
  type BitMappingEntry,
  type DefaultGroup,
} from './resource-catalog.js'
